# Generated by Django 4.1.3 on 2023-04-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress_report',
            fields=[
                ('Unique_Site_Id_As_per_central_DPR', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Circle', models.CharField(max_length=100)),
                ('Site_ID', models.CharField(max_length=100)),
                ('Site_Name', models.CharField(max_length=100)),
                ('Activity_Name', models.CharField(max_length=100)),
                ('Activity_Discription', models.CharField(max_length=100)),
                ('Line_Item', models.CharField(max_length=100)),
                ('Alotment_date_To_Vendor', models.DateField()),
                ('Vendor_Name', models.CharField(max_length=100)),
                ('Vendor_Code', models.CharField(max_length=100)),
                ('Activity_Date', models.DateField()),
                ('Activity_Completion_Status', models.CharField(max_length=100)),
                ('Material_Reco_Status', models.CharField(max_length=100)),
                ('Material_Reco_Date', models.DateField()),
                ('Activity_AT_Status', models.CharField(max_length=100)),
                ('Activity_AT_Date', models.DateField()),
            ],
        ),
    ]
