# Generated by Django 4.1.3 on 2023-04-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress_report',
            name='Activity_AT_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='progress_report',
            name='Activity_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='progress_report',
            name='Alotment_date_To_Vendor',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='progress_report',
            name='Material_Reco_Date',
            field=models.DateField(null=True),
        ),
    ]
