# Generated by Django 4.1.3 on 2023-04-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0002_alter_progress_report_activity_at_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress_report',
            name='Invoice_No',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress_report',
            name='Vendor_Invoice_Approval_Name_from_Central',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress_report',
            name='Vendor_Invoice_Approval_Name_from_Circle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress_report',
            name='Vendor_Invoice_Eligiblity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress_report',
            name='Vendor_PO_Approval_Name_Central',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress_report',
            name='Vendor_PO_Approval_Name_Circle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress_report',
            name='Vendor_PO_Date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='progress_report',
            name='Vendor_PO_Eligible',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='progress_report',
            name='Vendor_PO_No',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
