# Generated by Django 4.1.3 on 2023-04-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0003_progress_report_invoice_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload_status',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('update_status', models.CharField(blank=True, max_length=100, null=True)),
                ('Remark', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
