# Generated by Django 4.1.3 on 2023-04-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0008_vendor_po_no_upload_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='circle_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
