# Generated by Django 4.1.3 on 2023-02-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_post_report',
            name='id',
        ),
        migrations.AlterField(
            model_name='pre_post_report',
            name='Post_cell_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
