# Generated by Django 4.1.3 on 2023-02-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0003_remove_pre_post_report_post_data_volume_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
