# Generated by Django 4.1.3 on 2023-02-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0004_alter_pre_post_report_pre_volte_traffic_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_1',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
