# Generated by Django 4.1.3 on 2023-02-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0005_alter_pre_post_report_pre_volte_traffic_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_1',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_10',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_11',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_12',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_13',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_14',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_15',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_16',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_17',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_18',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_19',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_2',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_20',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_21',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_22',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_23',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_24',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_25',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_26',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_27',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_28',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_29',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_3',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_30',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_31',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_4',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_5',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_6',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_7',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_8',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Data_Volume_9',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_1',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_10',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_11',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_12',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_13',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_14',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_15',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_16',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_17',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_18',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_19',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_2',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_20',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_21',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_22',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_23',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_24',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_25',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_26',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_27',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_28',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_29',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_3',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_30',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_31',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_4',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_5',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_6',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_7',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_8',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_Volte_Traffic_9',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_1',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_10',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_11',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_12',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_13',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_14',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_15',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_16',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_17',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_18',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_19',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_2',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_20',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_21',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_22',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_23',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_24',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_25',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_26',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_27',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_28',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_29',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_3',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_30',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_31',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_4',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_5',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_6',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_7',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_8',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Data_Volume_9',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_10',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_11',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_12',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_13',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_14',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_15',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_16',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_17',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_18',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_19',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_2',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_20',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_21',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_22',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_23',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_24',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_25',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_26',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_27',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_28',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_29',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_3',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_30',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_31',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_4',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_5',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_6',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_7',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_8',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_Volte_Traffic_9',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
    ]
