# Generated by Django 4.1.3 on 2023-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0006_pre_post_report_post_data_volume_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_post_report',
            name='Post_trend_cell',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report',
            name='Pre_trend_cell',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
