# Generated by Django 4.1.3 on 2023-02-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0008_pre_post_report2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pre_post_report2',
            new_name='pre_post_2report',
        ),
    ]
