# Generated by Django 4.1.3 on 2023-02-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0009_rename_pre_post_report2_pre_post_2report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pre_post_2report',
            new_name='pre_post_report2',
        ),
    ]
