# Generated by Django 4.1.3 on 2023-02-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0010_rename_pre_post_2report_pre_post_report2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_post_report2',
            name='Pre_offered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
