# Generated by Django 4.1.3 on 2023-02-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0011_alter_pre_post_report2_pre_offered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_post_report2',
            name='Post_offered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
