# Generated by Django 4.1.3 on 2023-02-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0012_alter_pre_post_report2_post_offered_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Post_Date_Volume_Day7',
            new_name='Post_Data_Volume_Day7',
        ),
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Pre_Date_Volume_Day1',
            new_name='Pre_Data_Volume_Day1',
        ),
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Pre_Date_Volume_Day2',
            new_name='Pre_Data_Volume_Day2',
        ),
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Pre_Date_Volume_Day3',
            new_name='Pre_Data_Volume_Day3',
        ),
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Pre_Date_Volume_Day4',
            new_name='Pre_Data_Volume_Day4',
        ),
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Pre_Date_Volume_Day5',
            new_name='Pre_Data_Volume_Day5',
        ),
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Pre_Date_Volume_Day6',
            new_name='Pre_Data_Volume_Day6',
        ),
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Pre_Date_Volume_Day7',
            new_name='Pre_Data_Volume_Day7',
        ),
    ]
