# Generated by Django 4.1.3 on 2023-02-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0014_pre_post_report2_post_data_volume_day1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_post_report2',
            name='Post_Data_Volume_MAX',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report2',
            name='Post_Volte_Traffic_MAX',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report2',
            name='Pre_Data_Volume_MAX',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report2',
            name='Pre_Volte_Traffic_MAX',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
    ]
