# Generated by Django 4.1.3 on 2023-02-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0015_pre_post_report2_post_data_volume_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Post_Data_Volume_MAX',
            new_name='Post_Data_Volume_AVG',
        ),
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Post_Volte_Traffic_MAX',
            new_name='Post_Volte_Traffic_AVG',
        ),
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Pre_Data_Volume_MAX',
            new_name='Pre_Data_Volume_AVG',
        ),
        migrations.RenameField(
            model_name='pre_post_report2',
            old_name='Pre_Volte_Traffic_MAX',
            new_name='Pre_Volte_Traffic_AVG',
        ),
    ]
