# Generated by Django 4.1.3 on 2023-02-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0016_rename_post_data_volume_max_pre_post_report2_post_data_volume_avg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_post_report2',
            name='Percentage_change_Data_Volume',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='pre_post_report2',
            name='Percentage_change_Volte_Traffic',
            field=models.FloatField(blank=True, default=0.0, max_length=100),
        ),
    ]
