# Generated by Django 4.1.3 on 2023-02-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0018_rename_post_offered_date_pre_post_report2_relocation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pre_post_report_siteWise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_cell_site_id', models.CharField(blank=True, max_length=100)),
                ('Pre_cell_site_id', models.CharField(blank=True, max_length=100)),
                ('Today_date', models.DateField(blank=True, null=True)),
                ('Relocation_date', models.DateField(blank=True, null=True)),
                ('Pre_Volte_Traffic_Day1', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Volte_Traffic_Day2', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Volte_Traffic_Day3', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Volte_Traffic_Day4', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Volte_Traffic_Day5', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Volte_Traffic_Day6', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Volte_Traffic_Day7', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Volte_Traffic_Day1', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Volte_Traffic_Day2', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Volte_Traffic_Day3', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Volte_Traffic_Day4', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Volte_Traffic_Day5', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Volte_Traffic_Day6', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Volte_Traffic_Day7', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Data_Volume_Day1', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Data_Volume_Day2', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Data_Volume_Day3', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Data_Volume_Day4', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Data_Volume_Day5', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Data_Volume_Day6', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Data_Volume_Day7', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Data_Volume_Day1', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Data_Volume_Day2', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Data_Volume_Day3', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Data_Volume_Day4', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Data_Volume_Day5', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Data_Volume_Day6', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Data_Volume_Day7', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Volte_Traffic_AVG', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Volte_Traffic_AVG', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Pre_Data_Volume_AVG', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Post_Data_Volume_AVG', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Percentage_change_Volte_Traffic', models.FloatField(blank=True, default=0.0, max_length=100)),
                ('Percentage_change_Data_Volume', models.FloatField(blank=True, default=0.0, max_length=100)),
            ],
        ),
    ]
