# Generated by Django 4.1.3 on 2023-02-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0019_pre_post_report_sitewise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_post_report2',
            name='Post_trend_cell',
        ),
        migrations.RemoveField(
            model_name='pre_post_report2',
            name='Pre_trend_cell',
        ),
    ]
