# Generated by Django 4.1.3 on 2023-02-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0021_pre_post_report2_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_post_report_sitewise',
            name='Blank',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
