# Generated by Django 4.1.3 on 2023-03-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0022_pre_post_report_sitewise_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='raw_kpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Original_trend/Raw_Kpis/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
