# Generated by Django 4.1.3 on 2023-03-17 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0023_raw_kpis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_kpis',
            name='id',
        ),
        migrations.AddField(
            model_name='raw_kpis',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 17, 8, 24, 30, 19880, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
