# Generated by Django 4.1.3 on 2023-03-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0024_remove_raw_kpis_id_raw_kpis_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_kpis',
            name='date',
        ),
        migrations.AlterField(
            model_name='raw_kpis',
            name='upload_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
