# Generated by Django 4.1.5 on 2023-03-22 07:42

import Original_trend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Original_trend', '0025_remove_raw_kpis_date_alter_raw_kpis_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='integrated_sites',
            fields=[
                ('Site', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='raw_kpis',
            name='file',
            field=models.FileField(upload_to=Original_trend.models.get_file_path),
        ),
    ]
