# Generated by Django 4.1.3 on 2023-01-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0024_dpr_table1_internal_ms1_vs_ms2_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpr_table1',
            name='Internal_Ms1_Vs_Ms2_In_days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dpr_table1',
            name='Internal_RFAI_Vs_Ms1_In_Days',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
