# Generated by Django 4.1.3 on 2023-04-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soft_at_table',
            name='OA_COMMERCIAL_TRAFFIC_PUT_ON_AIR_MS1_DATE',
        ),
        migrations.RemoveField(
            model_name='soft_at_table',
            name='RFAI_DATE',
        ),
    ]
