# Generated by Django 4.1.3 on 2023-04-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_APP', '0002_remove_soft_at_table_oa_commercial_traffic_put_on_air_ms1_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soft_At_upload_status',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('update_status', models.CharField(blank=True, max_length=100, null=True)),
                ('Remark', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
