# Generated by Django 4.1.3 on 2023-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_APP', '0003_soft_at_upload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_upload_status',
            name='Site_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
