# Generated by Django 4.1.3 on 2023-04-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soft_AT_APP', '0004_soft_at_upload_status_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_at_table',
            name='Alarm_Bucket',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soft_at_table',
            name='Pending_Bucket',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
